### ISSUE TITLE
DLNA audio sink is not created in pavucontrol, in Slackware64 14.2 host

### ISSUE THREAD

**Issue by cmeljakovo** [sesceu/docker-pulseaudio-dlna#1]
Hi,

Could you provide the recipe to properly start the container, so dlna sink is created in pavucontrol, please?
I have got to the point, where I can start the container, the DLNA renderers are discovered, but not able to see the audio sink in pavucontrol.
I have tried on Slackware64 14.2 and Debian Jessie, with the same results.

[pa-dlna-debug.txt](https://github.com/sesceu/docker-pulseaudio-dlna/files/682380/pa-dlna-debug.txt)

The steps I followed:
xhost local:root
pactl load-module module-dbus-protocol
docker run -d --net host -v /etc/passwd:/etc/passwd --user oozzy sesceu/pulseaudio-dlna --debug

Attached is the debug log.

I appreciate your help.

**Comment by cmeljakovo** [comment]
This is the error encountered:

01-03 18:10:46 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
01-03 18:10:46 pulseaudio_dlna.application                    INFO     Codec settings:
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16" backend="generic">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
01-03 18:10:46 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 527, in run
    self._connect(signals)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 51, in _connect
    self.bus = self._get_bus()
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 97, in _get_bus
    stdout=subprocess.PIPE).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by cmeljakovo** [comment]
I have tested the container in other distros as well (Mint Cinamon 18.1, Debian Jessie/KDE, Debian/, Ubuntu 16.04) with same results.
The pulseaudio-dlna runs, but no audio sink is ever created.

Could you advise what recipe to use, to run the container successfully, or if I am missing something else?

Thank you.

**Comment by cmeljakovo** [comment]
Hi,

If the project is still maintained, could you give me a hint, please?
How do you use pulseaudio-dlna within the container, to control the dbus and creating ausio sink(s) on the host?
Do you use original program, where pactl commands are used?

Your help would be much appreciated!

**Comment by sesceu** [comment]
Hi,

sorry that it took me so long to answer. It is holiday season here so I don't regularly check my inbox.

Unfortunately, I'm currently not using the image anymore, so maintenance is currently on hold. In the foreseeable future I will get back to the project, but that might very well be 3-6 month.

I'm sorry, that I don't have better news for you, but you might just go ahead and fork the project.

Regards,

Sebastian


Am 6. Januar 2017 17:34:45 MEZ schrieb cmeljakovo <notifications@github.com>:

**Comment by cmeljakovo** [comment]
Hi Sebastian,

No worries, it is not a matter of "life", just playing with the pa-dlna, since I've found it very attractive for my application, to be able to stream sound over network.
I appreciate your answer, and I think I am on the right track to resolve this, just don't have too much time to spend as I would wish to. 

It seem to me, after discussing with the author of pa-dlna, to be able to execute pactl commands on host, within container, that's "all"...

Once I've resolved the puzzle, will post my findings happily.

Thanks again,

Ed
